theme: jekyll-theme-slate
title: Anant Krishna Mahale
description: Graduate Student at UNSW. \
My interest include Image Processing, Object Detection and Recognition, Deep Learning and Machine Learning. 
