theme: jekyll-theme-slate
title: Anant Krishna Mahale
description: >-
  Graduate Student at UNSW Sydney.
  My interest include Image Processing, Object Detection and Recognition, Deep Learning and Machine Learning. 
  This github page was create to showcase all the completed courses and thier respective projects done during Masters. 
github_username: anantkm
linkedin_username: anantkmahale
